### ISSUE TITLE
Label forced to '1' instead of 'test' if the population plot has one entry

### ISSUE THREAD

**Issue by biohisham** [plotrix/plotrix#3]
Example reproducing the bug:

`
library(plotrix)

pyramid.plot(10,
             5,
             labels="test",
)
`

commenting out  in the package sourcecode the line  `if (length(labels) == 1) ` restores the expected labelling.

for context on the bug refer to [stackoverflow post](https://stackoverflow.com/questions/76692104/recover-from-r-plotrix-forcing-the-label-to-1-if-the-population-plot-has-one-e)

**Comment by dmurdoch** [comment]
As I reported in #4, I have taken over as a maintainer of `plotrix`, and have moved the source to https://github.com/dmurdoch/plotrix . I will fix this bug in the first submission to CRAN.
