### ISSUE TITLE
Jim Lemon has died

### ISSUE THREAD

**Issue by dmurdoch** [plotrix/plotrix#4]
I am sorry to report that Jim Lemon, the main author and maintainer of `plotrix`, passed away in September 2023. 

 I (Duncan Murdoch) have volunteered to take over as a maintainer of the package.  I don't expect to add many functions to it, but I will attempt to address bugs and requests from CRAN so that it will continue to be available there.  Bug reports should be submitted at https://github.com/dmurdoch/plotrix/issues .

**Comment by darshanbaral** [comment]
This is shocking and sad news.

@dmurdoch, let me know what you want me to do with this github repo and github organization.

**Comment by dmurdoch** [comment]
@darshanbaral :  Could you get in touch with me by email?  My update of `plotrix` is now on CRAN, and my email is in the Maintainer field there.  After an update to version 3.8-4, run `maintainer(plotrix)` to see it.
